services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
    # ports:   #Non piu esposta all' host per sicurezza
    #   - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - proxy
      
  migrator:
    # image: todo-app
    build: .
    command: sh -c "./wait-for-postgres.sh && /todo/bin/todo eval 'Todo.Release.migrate()'"
    depends_on:
      db:
        condition: service_started
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
      DB_HOSTNAME: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: todo_dev
      RELEASE_COOKIE: "my_super_secret_cookie" 

    networks:
      - proxy

  todo_proxy:
    container_name: traefik-proxy

    image: traefik:v3.5.0
    networks:
      - proxy
    # command:
    #   - "--api.insecure=true"
    #   - "--providers.docker=true"
    #   - "--entrypoints.web.address=:80"
    ports:
      # Porta 80 per il traffico web e 8080 per la dashboard di Traefik
      - "80:80"
      - "8080:8080"
      - "443:443"  

    volumes:
      # Montiamo il socket di Docker per permettere a Traefik di scoprire gli altri container
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
       # - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    group_add:
      - "987"
    security_opt:
      - "apparmor=unconfined"
    # user: "root:root"
 
  # app:
  #   build: .
  #   command: sh -c "./wait-for-postgres.sh && /todo/bin/todo start"
  #   depends_on:
  #     migrator:
  #       condition: service_completed_successfully
  #     db:
  #       condition: service_started
  #   ports:
  #     - "5454"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: todo_dev
  #     DB_HOSTNAME: db
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: postgres
  #     DB_DATABASE: todo_dev
  #     RELEASE_COOKIE: "my_super_secret_cookie"
  #     RELEASE_NAME: "todo"
  #     HOSTNAME: app

  app-seed:
    image: todo-app
    build: .
    hostname: app-seed # <-- Hostname fisso
    command: sh -c "./wait-for-postgres.sh && /todo/bin/todo start"
    depends_on:
      migrator: 
        condition: service_completed_successfully 
    # ports:   #Le porte non sono piu esposte all' host, ci pensa traefik
    #   - "5454:5454" # Porta fissa
    expose:
      - "5454"
    environment:
      POSTGRES_USER: postgres
      DB_HOSTNAME: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
      #Per il cluster
      RELEASE_COOKIE: "my_super_secret_cookie"
      RELEASE_NAME: "todo"

    networks:
      - proxy
    
    labels: 
      #Istruzioni per traefik
      - "traefik.enable=true"

      - "traefik.http.routers.todo-cluster.rule=Host(`todo.localhost`)"
      - "traefik.http.routers.todo-cluster.entrypoints=web"
      - "traefik.http.routers.todo-http.middlewares=https-redirect@file" # collegamento a config/conf/middlewares.yaml
      - "traefik.http.routers.todo-http.service=todo-cluster"

      - "traefik.http.routers.todo-https.rule=Host(`todo.localhost`)"
      - "traefik.http.routers.todo-https.entrypoints=websecure"
      - "traefik.http.routers.todo-https.service=todo-cluster"
      - "traefik.http.routers.todo-https.tls=true" # Abilita TLS!
      
      - "traefik.http.services.todo-cluster.loadbalancer.server.port=5454"

  app-follower:
    image: todo-app
    build: .
    # Non ha bisogno di un hostname fisso
    command: sh -c "./wait-for-postgres.sh && /todo/bin/todo start"
    depends_on:
      app-seed: # Si avvia dopo il seed
        condition: service_started
    # ports:
    #   - "5454" #porte dinamiche
    expose:
      - "5454"
    environment:
      DB_HOSTNAME: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
      
      RELEASE_COOKIE: "my_super_secret_cookie"
      RELEASE_NAME: "todo"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.todo-cluster.rule=Host(`todo.localhost`)"
      - "traefik.http.routers.todo-cluster.entrypoints=web"
      - "traefik.http.routers.todo-http.middlewares=https-redirect@file"
      - "traefik.http.routers.todo-http.service=todo-cluster"

      - "traefik.http.routers.todo-https.rule=Host(`todo.localhost`)"
      - "traefik.http.routers.todo-https.entrypoints=websecure"
      - "traefik.http.routers.todo-https.service=todo-cluster"
      - "traefik.http.routers.todo-https.tls=true" # Abilita TLS!
      
      - "traefik.http.services.todo-cluster.loadbalancer.server.port=5454"

    networks:
      - proxy

networks:
  proxy:
    name: proxy
      
volumes:
  db_data:

